# This workflow will install Python dependencies, run tests and lint with a single version of Python on both Ubuntu and Windows
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Develop

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
    - name: Install requirements.txt ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install requirements.txt windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        if(Test-Path .\requirements.txt -PathType Leaf){pip install -r .\requirements.txt}
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov